import React from "react";
import Head from "next/head";
import { getSession } from "next-auth/react";
import { GetServerSidePropsContext } from "next";
import HomePage from "@/components/modules/home";

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <HomePage />
    </>
  );
}

export async function getServerSideProps(context: GetServerSidePropsContext) {
  const session = await getSession(context);

  return {
    props: {
      session: session === null ? undefined : session,
    },
  };
}
