import Head from "next/head";
import { api } from "@/utils/api";
import { useSession } from "next-auth/react";
import { Role } from "@prisma/client";

export default function Home() {
  const { data: sessionData } = useSession();
  const { data } = api.user.get.useQuery();

  const { mutateAsync: updateRoleAsync } = api.user.updateRole.useMutation();

  async function changeRole(id: string) {
    await updateRoleAsync({ id, role: Role.USER });
  }

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="h-screen overflow-auto">
        {JSON.stringify(sessionData)}
        <ul>
          {data
            ? data.map((item) => (
                <li
                  key={item.id}
                  className="cursor-pointer p-4 mb-2 bg-gray-100"
                  onClick={async () => await changeRole(item.id)}
                >
                  {item.name} - <span>{item.role}</span>
                </li>
              ))
            : null}
        </ul>
      </main>
    </>
  );
}
